AWSTemplateFormatVersion: 2010-09-09

Parameters:
  OIDCRoleStackName:
    Description: Name of the stack that created the OIDC role for GitHub Actions case sensitive
    Type: String

Resources:
  TerraformBackend:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: ec2-instance-roadmap
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  TerraformBackendPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TerraformBackend
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                Fn::ImportValue:
                  !Sub "${OIDCRoleStackName}--Role"
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Resource:
              - !Sub "arn:aws:s3:::${TerraformBackend}/*"
              - !Sub "arn:aws:s3:::${TerraformBackend}"
