name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_VAR_pvt_key: ${{ secrets.SSH_PRIV_KEY }}

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    env:
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_my-machine-pub-key: ${{ vars.PUB_KEY }}
      TF_VAR_apex-domain: ${{ vars.APEX_DOMAIN }}
      TF_VAR_subdomain: ${{ vars.SUBDOMAIN }}
      TF_VAR_acme-email: ${{ vars.ACME_EMAIL }}
    outputs:
      ec2_pub_ip: ${{ steps.terraform-ec2_public_ip.outputs.ec2_public_ip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -no-color --auto-approve

      - name: Terraform save output
        id: terraform-ec2_public_ip
        run: echo "ec2_public_ip=$(terraform output -raw ec2_public_ip)" >> "$GITHUB_OUTPUT"

  deploy-website:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: site_files
          sparse-checkout-cone-mode: false
      - name: Deploy site files to Nginx
        env:
          EC2_PUB_IP: ${{ needs.deploy-infrastructure.outputs.ec2_pub_ip }}
        run: |
          ls -larth site_files
          echo $EC2_PUB_IP
